#!/bin/bash

base=$(readlink -e $(dirname "$0"))
cd "$base"

date=$(date --rfc-3339=seconds 2>/dev/null)
[[ -z $date ]] && date="unknown"

sha=$(git rev-parse HEAD 2>/dev/null)
[[ -z $sha ]] && sha="unknown"

state="unknown"
if [[ $sha != "unknown" ]]; then
    tmp=$(git ls-files -mud 2>/dev/null)
    state="clean"
    [[ -n $tmp ]] && state="dirty"
fi

if [[ -f $base/VERSION ]]; then
    version=$(head -n 1 "$base/VERSION" 2>/dev/null)
fi
[[ -z $version ]] && version="unknown"

echo "Generating $base/version.go"
{
    echo "package main"
    echo ""
    echo "// Auto-generated by go_ver.sh"
    echo "var BuildInfo = map[string]string{"
    echo -e "\t\"date\":    \"$date\","
    echo -e "\t\"sha\":     \"$sha\","
    echo -e "\t\"state\":   \"$state\","
    echo -e "\t\"version\": \"$version\","
    echo "}"
} > "$base/version.go"

exit 0
